name: Trip app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci

      - name: Test frontend
        run: |
          ls
#          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI